name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  build:
    environment: default
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: "18.12"
          registry-url: "https://registry.npmjs.org"
      - name: Clean install dependencies
        run: npm ci
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
